Add system demo examples
alan-turing-institute/prompto pull request #77
Opened 2024-07-10 17:24 UTC by rchan26

2024-07-11 16:05 UTC, edchapman88 requested changes
Looks great! Found a typo (hence the `request changes`), left a few re-wording suggestions, and a couple of very optional suggestions (cutting a large section from experiment 3, and moving the naive sync send function to be visible in the notebook code). So cool to see the numbers on the page about how fast it is, great work!

2024-07-12 12:50 UTC, rchan26 commented on examples/system-demo/experiment_3.ipynb
> +  },
good point. we do use these results in the paper though, I'll swap the orders around

2024-07-12 12:51 UTC, rchan26 commented on examples/system-demo/experiment_3.ipynb
> +    "Note that in the [previous experiment](./experiment_2.ipynb), we also used parallel processing but in a slightly different way as we were parallelising the querying of different APIs."
I'll make it a header to signify this more

2024-07-12 12:58 UTC, rchan26 commented on examples/system-demo/api_utils.py
> +    return [send_prompt(prompt_dict) for prompt_dict in tqdm(prompt_dicts)]
yeah I think this is a good idea, duplication isn't too big of a problem I guess in this case

2024-07-12 13:14 UTC, merged